---
detectors:
  IrresponsibleModule:
    enabled: false
  TooManyStatements:
    enabled: true
    exclude:
      - 'TableService#slots'
      - 'ListService#list'
  UtilityFunction:
    enabled: true
    exclude:
      - 'ReserveService#remaining_slots'
  FeatureEnvy:
    enabled: true
    exclude:
      - 'TablesController#time'
      - 'Table#reservations_on_date'
  RepeatedConditional:
    enabled: true
  TooManyMethods:
    enabled: true

directories:
  "config/":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/":
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/services":
    UncommunicativeVariableName:
      enabled: true
      exclude:
        - 'TableService#slots'
    NestedIterators:
      enabled: true
      exclude:
        - 'ListService#list'
  "app/jobs":
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      enabled: false
    UtilityFunction:
      enabled: false
  "app/controllers":
    InstanceVariableAssumption:
      enabled: false
    IrresponsibleModule:
      enabled: false
    NestedIterators:
      max_allowed_nesting: 2
    UnusedPrivateMethod:
      enabled: false
    UncommunicativeModuleName:
      enabled: true
    DuplicateMethodCall:
      enabled: true
      max_calls: 2
    TooManyMethods:
      enabled: true
  "lib/":
    IrresponsibleModule:
      enabled: false
  "db/migrate":
    IrresponsibleModule:
      enabled: false
    FeatureEnvy:
      enabled: false
    UncommunicativeVariableName:
      enabled: false
  "spec/":
    IrresponsibleModule:
      enabled: false
    UncommunicativeMethodName:
      enabled: false
    UtilityFunction:
      enabled: false

exclude_paths:
  - bin/
  - vendor/
  - temp/
  - test/
  - public/
  - log/
  - db/